package com.cloud.pay.trade.mapper;

import com.cloud.pay.trade.entity.MerchantRouteConf;

public interface MerchantRouteConfMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    int insert(MerchantRouteConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    int insertSelective(MerchantRouteConf record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    MerchantRouteConf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    int updateByPrimaryKeySelective(MerchantRouteConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_route_conf
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    int updateByPrimaryKey(MerchantRouteConf record);
}