package com.cloud.pay.trade.mapper;

import com.cloud.pay.trade.dto.TradeDTO;
import com.cloud.pay.trade.entity.Trade;
import com.cloud.pay.trade.entity.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    Trade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated Sun Sep 09 10:52:02 CST 2018
     */
    int updateByPrimaryKey(Trade record);
    
    /**
     * 查询出交易订单存在但是渠道不存在的记录
     * @param reconDate
     * @return
     */
    List<TradeDTO> selectLongRecord(String reconDate);
    
    /**
     * 查询交易表和渠道订单号相同但其他要素不相等的记录
     * @param reconDate
     * @return
     */
    List<TradeDTO> selectExceptionRecord(String reconDate);
}