package com.cloud.pay.merchant.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantRouteConf {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant_route_conf.id
	 *
	 * @mbggenerated Wed Aug 29 20:34:49 CST 2018
	 */
	private Integer id;

	private Integer type;

	private Integer channelId;

	private Integer merchantId;

	private Integer loaning;

	private Integer loaningOrgId;

	private BigDecimal loaningAmount;

	private Integer status;

	private String creator;

	private Date createTime;

	private String modifer;

	private Date modifyTime;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getChannelId() {
		return channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	public Integer getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	public Integer getLoaning() {
		return loaning;
	}

	public void setLoaning(Integer loaning) {
		this.loaning = loaning;
	}

	public Integer getLoaningOrgId() {
		return loaningOrgId;
	}

	public void setLoaningOrgId(Integer loaningOrgId) {
		this.loaningOrgId = loaningOrgId;
	}

	public BigDecimal getLoaningAmount() {
		return loaningAmount;
	}

	public void setLoaningAmount(BigDecimal loaningAmount) {
		this.loaningAmount = loaningAmount;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getModifer() {
		return modifer;
	}
	
	public void setModifer(String modifer) {
		this.modifer = modifer == null ? null : modifer.trim();
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("MerchantRouteConf [id=");
		builder.append(id);
		builder.append(", type=");
		builder.append(type);
		builder.append(", channelId=");
		builder.append(channelId);
		builder.append(", merchantId=");
		builder.append(merchantId);
		builder.append(", loaning=");
		builder.append(loaning);
		builder.append(", loaningOrgId=");
		builder.append(loaningOrgId);
		builder.append(", loaningAmount=");
		builder.append(loaningAmount);
		builder.append(", status=");
		builder.append(status);
		builder.append(", creator=");
		builder.append(creator);
		builder.append(", createTime=");
		builder.append(createTime);
		builder.append(", modifer=");
		builder.append(modifer);
		builder.append(", modifyTime=");
		builder.append(modifyTime);
		builder.append("]");
		return builder.toString();
	}

}