package com.cloud.pay.merchant.entity;

public class MerchantChannel extends MerchantChannelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_channel.merchant_channel_code
     *
     * @mbggenerated Mon Sep 10 14:21:18 CST 2018
     */
    private String merchantChannelCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_channel.merchant_channel_code
     *
     * @return the value of t_merchant_channel.merchant_channel_code
     *
     * @mbggenerated Mon Sep 10 14:21:18 CST 2018
     */
    public String getMerchantChannelCode() {
        return merchantChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_channel.merchant_channel_code
     *
     * @param merchantChannelCode the value for t_merchant_channel.merchant_channel_code
     *
     * @mbggenerated Mon Sep 10 14:21:18 CST 2018
     */
    public void setMerchantChannelCode(String merchantChannelCode) {
        this.merchantChannelCode = merchantChannelCode == null ? null : merchantChannelCode.trim();
    }
}