package com.cloud.pay.merchant.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantPrepayJournal {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.trade_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private Integer tradeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.prepay_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private Integer prepayId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.amount
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private BigDecimal amount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.balance
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private BigDecimal balance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_merchant_prepay_journal.create_time
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	private Date createTime;

	private Integer debit;

	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.id
	 *
	 * @return the value of t_merchant_prepay_journal.id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.id
	 *
	 * @param id
	 *            the value for t_merchant_prepay_journal.id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.trade_id
	 *
	 * @return the value of t_merchant_prepay_journal.trade_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public Integer getTradeId() {
		return tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.trade_id
	 *
	 * @param tradeId
	 *            the value for t_merchant_prepay_journal.trade_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setTradeId(Integer tradeId) {
		this.tradeId = tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.prepay_id
	 *
	 * @return the value of t_merchant_prepay_journal.prepay_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public Integer getPrepayId() {
		return prepayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.prepay_id
	 *
	 * @param prepayId
	 *            the value for t_merchant_prepay_journal.prepay_id
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setPrepayId(Integer prepayId) {
		this.prepayId = prepayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.amount
	 *
	 * @return the value of t_merchant_prepay_journal.amount
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.amount
	 *
	 * @param amount
	 *            the value for t_merchant_prepay_journal.amount
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.balance
	 *
	 * @return the value of t_merchant_prepay_journal.balance
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.balance
	 *
	 * @param balance
	 *            the value for t_merchant_prepay_journal.balance
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_merchant_prepay_journal.create_time
	 *
	 * @return the value of t_merchant_prepay_journal.create_time
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_merchant_prepay_journal.create_time
	 *
	 * @param createTime
	 *            the value for t_merchant_prepay_journal.create_time
	 *
	 * @mbggenerated Sun Sep 30 11:33:59 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getDebit() {
		return debit;
	}

	public void setDebit(Integer debit) {
		this.debit = debit;
	}

	private Integer prepayTradeId;

	public Integer getPrepayTradeId() {
		return prepayTradeId;
	}

	public void setPrepayTradeId(Integer prepayTradeId) {
		this.prepayTradeId = prepayTradeId;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("MerchantPrepayJournal [id=");
		builder.append(id);
		builder.append(", tradeId=");
		builder.append(tradeId);
		builder.append(", prepayId=");
		builder.append(prepayId);
		builder.append(", amount=");
		builder.append(amount);
		builder.append(", balance=");
		builder.append(balance);
		builder.append(", createTime=");
		builder.append(createTime);
		builder.append(", debit=");
		builder.append(debit);
		builder.append(", type=");
		builder.append(type);
		builder.append(", prepayTradeId=");
		builder.append(prepayTradeId);
		builder.append("]");
		return builder.toString();
	}
	
}