package com.cloud.pay.merchant.entity;

import java.math.BigDecimal;

public class MerchantFeeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.pay_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer payFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.pay_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private BigDecimal payFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.loan_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer loanFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_fee_conf.loan_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private BigDecimal loanFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.id
     *
     * @return the value of t_merchant_fee_conf.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.id
     *
     * @param id the value for t_merchant_fee_conf.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.merchant_id
     *
     * @return the value of t_merchant_fee_conf.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.merchant_id
     *
     * @param merchantId the value for t_merchant_fee_conf.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.pay_fee_type
     *
     * @return the value of t_merchant_fee_conf.pay_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getPayFeeType() {
        return payFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.pay_fee_type
     *
     * @param payFeeType the value for t_merchant_fee_conf.pay_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setPayFeeType(Integer payFeeType) {
        this.payFeeType = payFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.pay_fee
     *
     * @return the value of t_merchant_fee_conf.pay_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public BigDecimal getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.pay_fee
     *
     * @param payFee the value for t_merchant_fee_conf.pay_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setPayFee(BigDecimal payFee) {
        this.payFee = payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.loan_fee_type
     *
     * @return the value of t_merchant_fee_conf.loan_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getLoanFeeType() {
        return loanFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.loan_fee_type
     *
     * @param loanFeeType the value for t_merchant_fee_conf.loan_fee_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setLoanFeeType(Integer loanFeeType) {
        this.loanFeeType = loanFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_fee_conf.loan_fee
     *
     * @return the value of t_merchant_fee_conf.loan_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public BigDecimal getLoanFee() {
        return loanFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_fee_conf.loan_fee
     *
     * @param loanFee the value for t_merchant_fee_conf.loan_fee
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setLoanFee(BigDecimal loanFee) {
        this.loanFee = loanFee;
    }
}