package com.cloud.pay.merchant.entity;

public class MerchantApplyAttachementInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_apply_attachement_info.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_apply_attachement_info.version
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_apply_attachement_info.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_apply_attachement_info.attachement_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private Integer attachementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_apply_attachement_info.attachement_path
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    private String attachementPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_apply_attachement_info.id
     *
     * @return the value of t_merchant_apply_attachement_info.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_apply_attachement_info.id
     *
     * @param id the value for t_merchant_apply_attachement_info.id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_apply_attachement_info.version
     *
     * @return the value of t_merchant_apply_attachement_info.version
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_apply_attachement_info.version
     *
     * @param version the value for t_merchant_apply_attachement_info.version
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_apply_attachement_info.merchant_id
     *
     * @return the value of t_merchant_apply_attachement_info.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_apply_attachement_info.merchant_id
     *
     * @param merchantId the value for t_merchant_apply_attachement_info.merchant_id
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_apply_attachement_info.attachement_type
     *
     * @return the value of t_merchant_apply_attachement_info.attachement_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public Integer getAttachementType() {
        return attachementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_apply_attachement_info.attachement_type
     *
     * @param attachementType the value for t_merchant_apply_attachement_info.attachement_type
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setAttachementType(Integer attachementType) {
        this.attachementType = attachementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_apply_attachement_info.attachement_path
     *
     * @return the value of t_merchant_apply_attachement_info.attachement_path
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public String getAttachementPath() {
        return attachementPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_apply_attachement_info.attachement_path
     *
     * @param attachementPath the value for t_merchant_apply_attachement_info.attachement_path
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    public void setAttachementPath(String attachementPath) {
        this.attachementPath = attachementPath == null ? null : attachementPath.trim();
    }
}