package com.cloud.pay.recon.entity;

import java.util.Date;

public class ReconExceptionBohai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon_exception_trade.ID
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon_exception_trade.ORDER_NO
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon_exception_trade.EXCEPTION_REASON
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    private String exceptionReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon_exception_trade.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon_exception_trade.ID
     *
     * @return the value of t_recon_exception_trade.ID
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon_exception_trade.ID
     *
     * @param id the value for t_recon_exception_trade.ID
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon_exception_trade.ORDER_NO
     *
     * @return the value of t_recon_exception_trade.ORDER_NO
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon_exception_trade.ORDER_NO
     *
     * @param orderNo the value for t_recon_exception_trade.ORDER_NO
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon_exception_trade.EXCEPTION_REASON
     *
     * @return the value of t_recon_exception_trade.EXCEPTION_REASON
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public String getExceptionReason() {
        return exceptionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon_exception_trade.EXCEPTION_REASON
     *
     * @param exceptionReason the value for t_recon_exception_trade.EXCEPTION_REASON
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public void setExceptionReason(String exceptionReason) {
        this.exceptionReason = exceptionReason == null ? null : exceptionReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon_exception_trade.CREATE_TIME
     *
     * @return the value of t_recon_exception_trade.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon_exception_trade.CREATE_TIME
     *
     * @param createTime the value for t_recon_exception_trade.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}