package com.cloud.pay.recon.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Recon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.ACCOUNT_DATE
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Date accountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.CHANNEL_ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.TRADE_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Integer tradeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.TRADE_AMT_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private BigDecimal tradeAmtTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.EXCEPTION_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Integer exceptionTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.RECON_STATUS
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Integer reconStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.FAIL_RESON
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private String failReson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_recon.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.ID
     *
     * @return the value of t_recon.ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.ID
     *
     * @param id the value for t_recon.ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.ACCOUNT_DATE
     *
     * @return the value of t_recon.ACCOUNT_DATE
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Date getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.ACCOUNT_DATE
     *
     * @param accountDate the value for t_recon.ACCOUNT_DATE
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setAccountDate(Date accountDate) {
        this.accountDate = accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.CHANNEL_ID
     *
     * @return the value of t_recon.CHANNEL_ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.CHANNEL_ID
     *
     * @param channelId the value for t_recon.CHANNEL_ID
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.TRADE_TOTAL
     *
     * @return the value of t_recon.TRADE_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Integer getTradeTotal() {
        return tradeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.TRADE_TOTAL
     *
     * @param tradeTotal the value for t_recon.TRADE_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setTradeTotal(Integer tradeTotal) {
        this.tradeTotal = tradeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.TRADE_AMT_TOTAL
     *
     * @return the value of t_recon.TRADE_AMT_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public BigDecimal getTradeAmtTotal() {
        return tradeAmtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.TRADE_AMT_TOTAL
     *
     * @param tradeAmtTotal the value for t_recon.TRADE_AMT_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setTradeAmtTotal(BigDecimal tradeAmtTotal) {
        this.tradeAmtTotal = tradeAmtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.EXCEPTION_TOTAL
     *
     * @return the value of t_recon.EXCEPTION_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Integer getExceptionTotal() {
        return exceptionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.EXCEPTION_TOTAL
     *
     * @param exceptionTotal the value for t_recon.EXCEPTION_TOTAL
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setExceptionTotal(Integer exceptionTotal) {
        this.exceptionTotal = exceptionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.RECON_STATUS
     *
     * @return the value of t_recon.RECON_STATUS
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Integer getReconStatus() {
        return reconStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.RECON_STATUS
     *
     * @param reconStatus the value for t_recon.RECON_STATUS
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setReconStatus(Integer reconStatus) {
        this.reconStatus = reconStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.FAIL_RESON
     *
     * @return the value of t_recon.FAIL_RESON
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public String getFailReson() {
        return failReson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.FAIL_RESON
     *
     * @param failReson the value for t_recon.FAIL_RESON
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setFailReson(String failReson) {
        this.failReson = failReson == null ? null : failReson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_recon.CREATE_TIME
     *
     * @return the value of t_recon.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_recon.CREATE_TIME
     *
     * @param createTime the value for t_recon.CREATE_TIME
     *
     * @mbggenerated Sun Sep 02 17:22:42 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}