package com.cloud.pay.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cloud.pay.common.entity.Bank;

public interface BankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	int insert(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	int insertSelective(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	Bank selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	int updateByPrimaryKeySelective(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_bank
	 *
	 * @mbggenerated Sun Aug 26 21:07:44 CST 2018
	 */
	int updateByPrimaryKey(Bank record);
	
	public List<Bank> getBankList(@Param("bankCode")String bankCode, @Param("bankName")String bankName);
}