package com.cloud.pay.common.mapper;

import com.cloud.pay.common.entity.Channel;
import com.cloud.pay.common.entity.ChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    Channel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbggenerated Sun Aug 26 21:07:44 CST 2018
     */
    int updateByPrimaryKey(Channel record);
}