package com.cloud.pay.recon.mapper;

import com.cloud.pay.recon.dto.FillRecordDTO;
import com.cloud.pay.recon.entity.FillRecord;
import com.cloud.pay.recon.entity.FillRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FillRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int countByExample(FillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int deleteByExample(FillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int insert(FillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int insertSelective(FillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    List<FillRecord> selectByExample(FillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    FillRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") FillRecord record, @Param("example") FillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int updateByExample(@Param("record") FillRecord record, @Param("example") FillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int updateByPrimaryKeySelective(FillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fill_record
     *
     * @mbggenerated Sun Sep 09 21:58:19 CST 2018
     */
    int updateByPrimaryKey(FillRecord record);
    
    /**
     * 查询资金补登列表
     * @return
     */
    List<FillRecordDTO> selectListByParam();
}