package com.cloud.pay.recon.mapper;

import com.cloud.pay.recon.entity.ReconChannelBohai;
import com.cloud.pay.recon.entity.ReconChannelBohaiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReconChannelBohaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int countByExample(ReconChannelBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int deleteByExample(ReconChannelBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int insert(ReconChannelBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int insertSelective(ReconChannelBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    List<ReconChannelBohai> selectByExample(ReconChannelBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    ReconChannelBohai selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReconChannelBohai record, @Param("example") ReconChannelBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByExample(@Param("record") ReconChannelBohai record, @Param("example") ReconChannelBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByPrimaryKeySelective(ReconChannelBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_channel_bohai
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByPrimaryKey(ReconChannelBohai record);
}