package com.cloud.pay.recon.mapper;

import com.cloud.pay.recon.entity.ReconExceptionBohai;
import com.cloud.pay.recon.entity.ReconExceptionBohaiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReconExceptionBohaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int countByExample(ReconExceptionBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int deleteByExample(ReconExceptionBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int insert(ReconExceptionBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int insertSelective(ReconExceptionBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    List<ReconExceptionBohai> selectByExample(ReconExceptionBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    ReconExceptionBohai selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReconExceptionBohai record, @Param("example") ReconExceptionBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int updateByExample(@Param("record") ReconExceptionBohai record, @Param("example") ReconExceptionBohaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int updateByPrimaryKeySelective(ReconExceptionBohai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon_exception_trade
     *
     * @mbggenerated Thu Sep 06 23:00:02 CST 2018
     */
    int updateByPrimaryKey(ReconExceptionBohai record);
    
    /**
      * 生成短款异常数据
     * @param reconDate
     */
    int insertShortPlat(String reconDate);
    
    
}