package com.cloud.pay.recon.mapper;

import com.cloud.pay.recon.dto.ReconDTO;
import com.cloud.pay.recon.entity.Recon;
import com.cloud.pay.recon.entity.ReconExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int countByExample(ReconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int deleteByExample(ReconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int insert(Recon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int insertSelective(Recon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    List<Recon> selectByExample(ReconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    Recon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Recon record, @Param("example") ReconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByExample(@Param("record") Recon record, @Param("example") ReconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByPrimaryKeySelective(Recon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recon
     *
     * @mbggenerated Sun Sep 02 12:55:14 CST 2018
     */
    int updateByPrimaryKey(Recon record);
    
    /**
     *  批量插入
     * @param list
     * @return
     */
    int batchInsert(List<Recon> list);
    
    /**
      * 对账列表查询
     * @param reconStatus
     * @param channelName
     * @param tradeDate
     * @return
     */
    List<ReconDTO> queryReconList(@Param("reconStatus")Integer reconStatus,@Param("channelName")String channelName,@Param("tradeDate")Date tradeDate);
    
    /**
     * 根据对账日期获取所有渠道的对账信息
     * @param reconDate
     * @return
     */
    List<Recon> selectListByReconDate(Date reconDate);

}