package com.cloud.pay.merchant.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cloud.pay.merchant.dto.MerchantApplyDTO;
import com.cloud.pay.merchant.entity.MerchantApplyBaseInfo;

public interface MerchantApplyBaseInfoMapper {
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_merchant_apply_base_info
	 *
	 * @mbggenerated Sun Sep 02 09:06:42 CST 2018
	 */
	int insert(MerchantApplyBaseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_merchant_apply_base_info
	 *
	 * @mbggenerated Sun Sep 02 09:06:42 CST 2018
	 */
	int insertSelective(MerchantApplyBaseInfo record);

	MerchantApplyBaseInfo selectByPrimaryKey(Integer id);

	int updateByPrimaryKeySelective(MerchantApplyBaseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_merchant_apply_base_info
	 *
	 * @mbggenerated Sun Sep 02 09:06:42 CST 2018
	 */
	int updateByPrimaryKey(MerchantApplyBaseInfo record);
	
	/**
	 * 查询机构申请信息
	 * @param orgId
	 * @param code
	 * @param name
	 * @param status
	 * @param startTime
	 * @param endTime
	 * @param type 类型
	 * @return
	 */
	List<MerchantApplyDTO> getOrgApplyDTOs(@Param("type") Integer type, @Param("code") String code,
			@Param("name") String name, @Param("status") Integer status, @Param("startTime") Date startTime,
			@Param("endTime") Date endTime);

	/**
	 * 查询商户申请信息
	 * @param orgId
	 * @param code
	 * @param name
	 * @param status
	 * @param startTime
	 * @param endTime
	 * @return
	 */
	List<MerchantApplyDTO> getMerchantApplyDTOs(@Param("orgId") Integer orgId, @Param("code") String code,
			@Param("name") String name, @Param("status") Integer status, @Param("startTime") Date startTime,
			@Param("endTime") Date endTime);

	/**
	 * 根据商户编码获取商户基本信息
	 * @param code
	 * @return
	 */
	MerchantApplyBaseInfo selectByCode(String code);
}