package com.cloud.pay.merchant.mapper;

import org.apache.ibatis.annotations.Param;

import com.cloud.pay.merchant.entity.MerchantFeeInfo;

public interface MerchantFeeInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insert(MerchantFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insertSelective(MerchantFeeInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    MerchantFeeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int updateByPrimaryKeySelective(MerchantFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int updateByPrimaryKey(MerchantFeeInfo record);
    
    MerchantFeeInfo selectByMerchantId(@Param("merchantId")Integer merchantId);
}
