package com.cloud.pay.merchant.mapper;

import com.cloud.pay.merchant.entity.MerchantApplyBaseInfo;

public interface MerchantApplyBaseInfoMapper {
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_base_info
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insert(MerchantApplyBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_base_info
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insertSelective(MerchantApplyBaseInfo record);

    MerchantApplyBaseInfo selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(MerchantApplyBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_base_info
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int updateByPrimaryKey(MerchantApplyBaseInfo record);
}