package com.cloud.pay.merchant.mapper;

import com.cloud.pay.merchant.entity.MerchantApplyFeeInfo;

public interface MerchantApplyFeeInfoMapper {
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insert(MerchantApplyFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int insertSelective(MerchantApplyFeeInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    MerchantApplyFeeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int updateByPrimaryKeySelective(MerchantApplyFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_apply_fee_conf
     *
     * @mbggenerated Sun Sep 02 09:06:42 CST 2018
     */
    int updateByPrimaryKey(MerchantApplyFeeInfo record);
    
    MerchantApplyFeeInfo selectByMerchantId(Integer id);
}