package com.cloud.pay.trade.entity;

import java.math.BigDecimal;

public class BatchTradeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.batch_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.payee_bank_acct_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private String payeeBankAcctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.payee_bank_acct_type
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private Integer payeeBankAcctType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.payee_bank_acct_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private String payeeBankAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.payee_bank_id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private Integer payeeBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.payee_bank_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private String payeeBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.amount
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_batch_trade_detail.remark
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.id
     *
     * @return the value of t_batch_trade_detail.id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.id
     *
     * @param id the value for t_batch_trade_detail.id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.batch_no
     *
     * @return the value of t_batch_trade_detail.batch_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.batch_no
     *
     * @param batchNo the value for t_batch_trade_detail.batch_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.payee_bank_acct_name
     *
     * @return the value of t_batch_trade_detail.payee_bank_acct_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public String getPayeeBankAcctName() {
        return payeeBankAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.payee_bank_acct_name
     *
     * @param payeeBankAcctName the value for t_batch_trade_detail.payee_bank_acct_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setPayeeBankAcctName(String payeeBankAcctName) {
        this.payeeBankAcctName = payeeBankAcctName == null ? null : payeeBankAcctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.payee_bank_acct_type
     *
     * @return the value of t_batch_trade_detail.payee_bank_acct_type
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public Integer getPayeeBankAcctType() {
        return payeeBankAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.payee_bank_acct_type
     *
     * @param payeeBankAcctType the value for t_batch_trade_detail.payee_bank_acct_type
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setPayeeBankAcctType(Integer payeeBankAcctType) {
        this.payeeBankAcctType = payeeBankAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.payee_bank_acct_no
     *
     * @return the value of t_batch_trade_detail.payee_bank_acct_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public String getPayeeBankAcctNo() {
        return payeeBankAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.payee_bank_acct_no
     *
     * @param payeeBankAcctNo the value for t_batch_trade_detail.payee_bank_acct_no
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setPayeeBankAcctNo(String payeeBankAcctNo) {
        this.payeeBankAcctNo = payeeBankAcctNo == null ? null : payeeBankAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.payee_bank_id
     *
     * @return the value of t_batch_trade_detail.payee_bank_id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public Integer getPayeeBankId() {
        return payeeBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.payee_bank_id
     *
     * @param payeeBankId the value for t_batch_trade_detail.payee_bank_id
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setPayeeBankId(Integer payeeBankId) {
        this.payeeBankId = payeeBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.payee_bank_name
     *
     * @return the value of t_batch_trade_detail.payee_bank_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public String getPayeeBankName() {
        return payeeBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.payee_bank_name
     *
     * @param payeeBankName the value for t_batch_trade_detail.payee_bank_name
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setPayeeBankName(String payeeBankName) {
        this.payeeBankName = payeeBankName == null ? null : payeeBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.amount
     *
     * @return the value of t_batch_trade_detail.amount
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.amount
     *
     * @param amount the value for t_batch_trade_detail.amount
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_batch_trade_detail.remark
     *
     * @return the value of t_batch_trade_detail.remark
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_batch_trade_detail.remark
     *
     * @param remark the value for t_batch_trade_detail.remark
     *
     * @mbggenerated Tue Sep 11 18:49:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}