package com.cloud.pay.trade.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantRouteConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.channel_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.merchant_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.loaning
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer loaning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.loaning_org_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer loaningOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.loaning_amount
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private BigDecimal loaningAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.status
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.creator
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.create_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.modifer
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private String modifer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_route_conf.modify_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.id
     *
     * @return the value of t_merchant_route_conf.id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.id
     *
     * @param id the value for t_merchant_route_conf.id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.channel_id
     *
     * @return the value of t_merchant_route_conf.channel_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.channel_id
     *
     * @param channelId the value for t_merchant_route_conf.channel_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.merchant_id
     *
     * @return the value of t_merchant_route_conf.merchant_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.merchant_id
     *
     * @param merchantId the value for t_merchant_route_conf.merchant_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.loaning
     *
     * @return the value of t_merchant_route_conf.loaning
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getLoaning() {
        return loaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.loaning
     *
     * @param loaning the value for t_merchant_route_conf.loaning
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setLoaning(Integer loaning) {
        this.loaning = loaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.loaning_org_id
     *
     * @return the value of t_merchant_route_conf.loaning_org_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getLoaningOrgId() {
        return loaningOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.loaning_org_id
     *
     * @param loaningOrgId the value for t_merchant_route_conf.loaning_org_id
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setLoaningOrgId(Integer loaningOrgId) {
        this.loaningOrgId = loaningOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.loaning_amount
     *
     * @return the value of t_merchant_route_conf.loaning_amount
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public BigDecimal getLoaningAmount() {
        return loaningAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.loaning_amount
     *
     * @param loaningAmount the value for t_merchant_route_conf.loaning_amount
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setLoaningAmount(BigDecimal loaningAmount) {
        this.loaningAmount = loaningAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.status
     *
     * @return the value of t_merchant_route_conf.status
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.status
     *
     * @param status the value for t_merchant_route_conf.status
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.creator
     *
     * @return the value of t_merchant_route_conf.creator
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.creator
     *
     * @param creator the value for t_merchant_route_conf.creator
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.create_time
     *
     * @return the value of t_merchant_route_conf.create_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.create_time
     *
     * @param createTime the value for t_merchant_route_conf.create_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.modifer
     *
     * @return the value of t_merchant_route_conf.modifer
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public String getModifer() {
        return modifer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.modifer
     *
     * @param modifer the value for t_merchant_route_conf.modifer
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setModifer(String modifer) {
        this.modifer = modifer == null ? null : modifer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_route_conf.modify_time
     *
     * @return the value of t_merchant_route_conf.modify_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_route_conf.modify_time
     *
     * @param modifyTime the value for t_merchant_route_conf.modify_time
     *
     * @mbggenerated Wed Aug 29 20:34:49 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}