package com.cloud.pay.trade.entity;

import java.util.Date;

public class PaySms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.batch_no
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.sms_code
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private String smsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.sms_biz_id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private String smsBizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.create_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.verfiy_result
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private Integer verfiyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.verify_times
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private Integer verifyTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sms.verify_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    private Date verifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.id
     *
     * @return the value of t_pay_sms.id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.id
     *
     * @param id the value for t_pay_sms.id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.batch_no
     *
     * @return the value of t_pay_sms.batch_no
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.batch_no
     *
     * @param batchNo the value for t_pay_sms.batch_no
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.sms_code
     *
     * @return the value of t_pay_sms.sms_code
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.sms_code
     *
     * @param smsCode the value for t_pay_sms.sms_code
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode == null ? null : smsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.sms_biz_id
     *
     * @return the value of t_pay_sms.sms_biz_id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public String getSmsBizId() {
        return smsBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.sms_biz_id
     *
     * @param smsBizId the value for t_pay_sms.sms_biz_id
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setSmsBizId(String smsBizId) {
        this.smsBizId = smsBizId == null ? null : smsBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.create_time
     *
     * @return the value of t_pay_sms.create_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.create_time
     *
     * @param createTime the value for t_pay_sms.create_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.verfiy_result
     *
     * @return the value of t_pay_sms.verfiy_result
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public Integer getVerfiyResult() {
        return verfiyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.verfiy_result
     *
     * @param verfiyResult the value for t_pay_sms.verfiy_result
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setVerfiyResult(Integer verfiyResult) {
        this.verfiyResult = verfiyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.verify_times
     *
     * @return the value of t_pay_sms.verify_times
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public Integer getVerifyTimes() {
        return verifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.verify_times
     *
     * @param verifyTimes the value for t_pay_sms.verify_times
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setVerifyTimes(Integer verifyTimes) {
        this.verifyTimes = verifyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sms.verify_time
     *
     * @return the value of t_pay_sms.verify_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public Date getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sms.verify_time
     *
     * @param verifyTime the value for t_pay_sms.verify_time
     *
     * @mbggenerated Mon Oct 08 15:29:45 CST 2018
     */
    public void setVerifyTime(Date verifyTime) {
        this.verifyTime = verifyTime;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PaySms [id=");
		builder.append(id);
		builder.append(", batchNo=");
		builder.append(batchNo);
		builder.append(", smsCode=");
		builder.append(smsCode);
		builder.append(", smsBizId=");
		builder.append(smsBizId);
		builder.append(", createTime=");
		builder.append(createTime);
		builder.append(", verfiyResult=");
		builder.append(verfiyResult);
		builder.append(", verifyTimes=");
		builder.append(verifyTimes);
		builder.append(", verifyTime=");
		builder.append(verifyTime);
		builder.append("]");
		return builder.toString();
	}
    
}